USE [master]
GO

/****** Object:  Database [Nutshell]    Script Date: 12/18/2019 12:56:24 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'Nutshell')
DROP DATABASE [Nutshell]
GO

USE [master]
GO

/****** Object:  Database [Nutshell]    Script Date: 12/18/2019 12:56:24 ******/
CREATE DATABASE [Nutshell] ON  PRIMARY 
( NAME = N'Nutshell', FILENAME = N'E:\Nutshell\Nutshell.mdf' , SIZE = 1920KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Nutshell_log', FILENAME = N'E:\Nutshell\Nutshell_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [Nutshell] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Nutshell].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Nutshell] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Nutshell] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Nutshell] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Nutshell] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Nutshell] SET ARITHABORT OFF 
GO

ALTER DATABASE [Nutshell] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Nutshell] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Nutshell] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [Nutshell] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Nutshell] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Nutshell] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Nutshell] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Nutshell] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Nutshell] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Nutshell] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Nutshell] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Nutshell] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Nutshell] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Nutshell] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Nutshell] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Nutshell] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Nutshell] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Nutshell] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Nutshell] SET  READ_WRITE 
GO

ALTER DATABASE [Nutshell] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Nutshell] SET  MULTI_USER 
GO

ALTER DATABASE [Nutshell] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Nutshell] SET DB_CHAINING OFF 
GO


